use std::{
    collections::{BTreeMap, hash_map::DefaultHasher},
    fmt,
    hash::{Hash, Hasher},
    ops::{Deref, DerefMut},
};

use leptos_fluent::{I18n, tr};
use reactive_stores::Store;
use serde::{Deserialize, Serialize};
use strum::{Display, EnumString};

use crate::{
    expr::DicePool,
    model::{ActionType, Die, SpellData, Translatable},
};

/// Identity slot a feature writes to when applied. Used both as the inner
/// discriminator for `FeatureCategory::System(_)` (auto-generated species /
/// background / subclass features) and on the legacy `grants` placeholder
/// path during the migration window.
#[derive(
    Debug,
    Clone,
    Copy,
    PartialEq,
    Eq,
    PartialOrd,
    Ord,
    Hash,
    Display,
    EnumString,
    Serialize,
    Deserialize
)]
pub enum IdentitySlot {
    Subclass,
    Species,
    Background,
    Class,
}

#[derive(
    Debug, Clone, Copy, Default, PartialEq, Eq, PartialOrd, Ord, Hash, EnumString
)]
pub enum FeatureCategory {
    #[default]
    Class,
    Origin,
    General,
    FightingStyle,
    EpicBoon,
    Generation,
    Faction,
    Dragonmark,
    /// Auto-generated by `RulesRegistry::synthesize_system_features` —
    /// one per available species / background / subclass. Each carries an
    /// assign that writes to the corresponding identity attribute.
    /// `#[strum(disabled)]`: only constructed in code, never parsed from a
    /// free-text route or expression.
    #[strum(disabled)]
    System(IdentitySlot),
}

impl FeatureCategory {
    /// Categories surfaced in the Reference page filter and the freestanding
    /// "Add Feat" picker. `System` entries are synthetic, only meaningful as
    /// `ReplaceWith::Category(System(_))` filter targets.
    pub const USER_FACING: &'static [Self] = &[
        Self::Class,
        Self::Origin,
        Self::General,
        Self::FightingStyle,
        Self::EpicBoon,
        Self::Generation,
        Self::Faction,
        Self::Dragonmark,
    ];

    /// Kebab-case slug for CSS class names (`feat-<slug>`).
    pub fn slug(&self) -> &'static str {
        match self {
            Self::Class => "class",
            Self::Origin => "origin",
            Self::General => "general",
            Self::FightingStyle => "fighting-style",
            Self::EpicBoon => "epic-boon",
            Self::Generation => "generation",
            Self::Faction => "faction",
            Self::Dragonmark => "dragonmark",
            Self::System(IdentitySlot::Subclass) => "system-subclass",
            Self::System(IdentitySlot::Species) => "system-species",
            Self::System(IdentitySlot::Background) => "system-background",
            Self::System(IdentitySlot::Class) => "system-class",
        }
    }
}

impl fmt::Display for FeatureCategory {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Class => f.write_str("Class"),
            Self::Origin => f.write_str("Origin"),
            Self::General => f.write_str("General"),
            Self::FightingStyle => f.write_str("FightingStyle"),
            Self::EpicBoon => f.write_str("EpicBoon"),
            Self::Generation => f.write_str("Generation"),
            Self::Faction => f.write_str("Faction"),
            Self::Dragonmark => f.write_str("Dragonmark"),
            Self::System(slot) => write!(f, "System.{slot}"),
        }
    }
}

impl Serialize for FeatureCategory {
    fn serialize<S: serde::Serializer>(&self, ser: S) -> Result<S::Ok, S::Error> {
        match self {
            Self::System(slot) => {
                use serde::ser::SerializeMap;
                let mut map = ser.serialize_map(Some(1))?;
                map.serialize_entry("System", slot)?;
                map.end()
            }
            other => ser.serialize_str(&other.to_string()),
        }
    }
}

impl<'de> Deserialize<'de> for FeatureCategory {
    fn deserialize<D: serde::Deserializer<'de>>(de: D) -> Result<Self, D::Error> {
        #[derive(Deserialize)]
        #[serde(untagged)]
        enum Repr {
            Tagged {
                #[serde(rename = "System")]
                system: IdentitySlot,
            },
            Bare(String),
        }
        match Repr::deserialize(de)? {
            Repr::Tagged { system } => Ok(Self::System(system)),
            Repr::Bare(s) => s
                .parse()
                .map_err(|_| serde::de::Error::custom(format!("unknown feature category: {s}"))),
        }
    }
}

impl Translatable for FeatureCategory {
    fn tr_key(&self) -> &'static str {
        match self {
            Self::Class => "feat-cat-class",
            Self::Origin => "feat-cat-origin",
            Self::General => "feat-cat-general",
            Self::FightingStyle => "feat-cat-fighting-style",
            Self::EpicBoon => "feat-cat-epic-boon",
            Self::Generation => "feat-cat-generation",
            Self::Faction => "feat-cat-faction",
            Self::Dragonmark => "feat-cat-dragonmark",
            Self::System(IdentitySlot::Subclass) => "feat-cat-system-subclass",
            Self::System(IdentitySlot::Species) => "feat-cat-system-species",
            Self::System(IdentitySlot::Background) => "feat-cat-system-background",
            Self::System(IdentitySlot::Class) => "feat-cat-system-class",
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Default, Store)]
pub struct Feature {
    #[serde(default)]
    pub name: Box<str>,
    #[serde(default)]
    pub label: Option<String>,
    #[serde(default)]
    pub description: String,
    #[serde(default)]
    pub applied: bool,
    #[serde(default)]
    pub category: FeatureCategory,
    #[serde(default)]
    pub source: FeatureSource,
    #[serde(default)]
    pub inputs: Vec<AssignInputs>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub replaces: Option<Box<str>>,
    /// Runtime-only soft-delete marker — kept in the Vec so reactive_stores
    /// indexers can't go out of bounds on the same tick. Dropped on save.
    #[serde(skip)]
    pub removed: bool,
}

impl Feature {
    pub fn label(&self) -> &str {
        self.label.as_deref().unwrap_or(&self.name)
    }

    pub fn set_label(&mut self, value: String) {
        self.label = Some(value);
    }

    pub fn dom_id(&self) -> String {
        feature_dom_id(&self.name, &self.source)
    }
}

pub fn feature_dom_id(name: &str, source: &FeatureSource) -> String {
    let mut h = DefaultHasher::new();
    name.hash(&mut h);
    source.hash(&mut h);
    format!("f-{:016x}", h.finish())
}

#[derive(
    Debug,
    Clone,
    Hash,
    PartialEq,
    Eq,
    PartialOrd,
    Ord,
    Serialize,
    Deserialize
)]
pub enum FeatureSource {
    Class(Box<str>, u32),
    Subclass(Box<str>, Box<str>, u32),
    #[serde(alias = "Race")]
    Species(Box<str>),
    Background(Box<str>),
    User(u32),
}

impl Default for FeatureSource {
    fn default() -> Self {
        Self::User(0)
    }
}

impl fmt::Display for FeatureSource {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Class(name, level) => write!(f, "Class: {name} ({level})"),
            Self::Subclass(class_name, subclass_name, level) => {
                write!(f, "Subclass: {class_name} - {subclass_name} ({level})")
            }
            Self::Species(name) => write!(f, "Species: {name}"),
            Self::Background(name) => write!(f, "Background: {name}"),
            Self::User(level) => write!(f, "User ({level})"),
        }
    }
}

impl FeatureSource {
    pub fn display_name(&self, i18n: I18n) -> Option<String> {
        match self {
            Self::Class(name, level) => {
                let prefix = tr!(i18n, "source-class");
                Some(format!("{prefix}: {name} ({level})"))
            }
            Self::Subclass(class, name, level) => {
                let prefix = tr!(i18n, "source-subclass");
                Some(format!("{prefix}: {class} — {name} ({level})"))
            }
            Self::Species(name) => {
                let prefix = tr!(i18n, "source-species");
                Some(format!("{prefix}: {name}"))
            }
            Self::Background(name) => {
                let prefix = tr!(i18n, "source-background");
                Some(format!("{prefix}: {name}"))
            }
            Self::User(_) => None,
        }
    }

    pub fn name(&self) -> &str {
        match self {
            Self::Class(name, _)
            | Self::Species(name)
            | Self::Background(name)
            | Self::Subclass(_, name, _) => name,
            Self::User(_) => "",
        }
    }

    pub fn is_user(&self) -> bool {
        matches!(self, Self::User(_))
    }

    pub fn as_class(&self) -> Option<&str> {
        match self {
            Self::Class(name, _) => Some(name),
            Self::Subclass(name, _, _) => Some(name),
            _ => None,
        }
    }

    pub fn added_at_level(&self) -> u32 {
        match self {
            Self::Class(_, level) | Self::User(level) | Self::Subclass(_, _, level) => *level,
            Self::Species(_) | Self::Background(_) => 1,
        }
    }
}

/// Container joining the applied feature list with per-feature data
/// (fields + spells). Co-located because the two are tightly coupled —
/// `data` entries are keyed by feature name and should exist for every
/// applied feature that has fields or spells.
///
/// `Deref`/`DerefMut` target the `BTreeMap<Box<str>, FeatureData>` data map
/// so map-style access (`.get()`, `.get_mut()`, `.insert()`, `.keys()`,
/// `.values()`, `.clear()`) works through the container directly. List
/// iteration and list-specific queries go through inherent methods
/// (`iter`, `contains`, `has`, `is_pending`, `put`, `get_inputs`,
/// `has_category`) which override the BTreeMap accessors where names
/// clash.
#[derive(Debug, Clone, Default, Serialize, Deserialize, Store)]
pub struct Features {
    #[serde(default, serialize_with = "serialize_visible_features")]
    pub list: Vec<Feature>,
    #[serde(
        default,
        deserialize_with = "crate::serde_util::deserialize_map_dropping_nulls"
    )]
    data: BTreeMap<Box<str>, FeatureData>,
}

/// Drop soft-removed rows on persistence; next load sees a compacted list.
fn serialize_visible_features<S>(list: &[Feature], s: S) -> Result<S::Ok, S::Error>
where
    S: serde::Serializer,
{
    s.collect_seq(list.iter().filter(|feature| !feature.removed))
}

impl Deref for Features {
    type Target = BTreeMap<Box<str>, FeatureData>;

    fn deref(&self) -> &Self::Target {
        &self.data
    }
}

impl DerefMut for Features {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.data
    }
}

impl<'a> IntoIterator for &'a Features {
    type IntoIter = std::slice::Iter<'a, Feature>;
    type Item = &'a Feature;

    fn into_iter(self) -> Self::IntoIter {
        self.list.iter()
    }
}

impl<'a> IntoIterator for &'a mut Features {
    type IntoIter = std::slice::IterMut<'a, Feature>;
    type Item = &'a mut Feature;

    fn into_iter(self) -> Self::IntoIter {
        self.list.iter_mut()
    }
}

impl Features {
    /// Construct from an existing list + data pair. Only used in tests where
    /// struct literals would otherwise need access to the private `data`
    /// field.
    #[cfg(test)]
    pub fn from_parts(list: Vec<Feature>, data: BTreeMap<Box<str>, FeatureData>) -> Self {
        Self { list, data }
    }

    /// Iterate live feature rows (skips soft-removed). Use `self.list.iter()`
    /// directly when raw access is needed (e.g. `<For>` keying).
    pub fn iter(&self) -> impl Iterator<Item = &Feature> + '_ {
        self.list.iter().filter(|feature| !feature.removed)
    }

    pub fn iter_mut(&mut self) -> impl Iterator<Item = &mut Feature> + '_ {
        self.list.iter_mut().filter(|feature| !feature.removed)
    }

    /// Number of feature rows (applied or pending).
    pub fn len(&self) -> usize {
        self.list.len()
    }

    /// True if no feature rows at all.
    pub fn is_empty(&self) -> bool {
        self.list.is_empty()
    }

    /// Read-only access to a row by position. Returns `None` for soft-removed.
    pub fn at(&self, pos: usize) -> Option<&Feature> {
        self.list.get(pos).filter(|feature| !feature.removed)
    }

    /// Mutable access to a row by position. Returns `None` for soft-removed.
    pub fn at_mut(&mut self, pos: usize) -> Option<&mut Feature> {
        self.list.get_mut(pos).filter(|feature| !feature.removed)
    }

    /// First live row matching `(name, source)`.
    pub fn find(&self, name: &str, source: &FeatureSource) -> Option<&Feature> {
        self.list
            .iter()
            .find(|feature| !feature.removed && &*feature.name == name && &feature.source == source)
    }

    pub fn find_mut(&mut self, name: &str, source: &FeatureSource) -> Option<&mut Feature> {
        self.list
            .iter_mut()
            .find(|feature| !feature.removed && &*feature.name == name && &feature.source == source)
    }

    pub fn find_pos(&self, name: &str, source: &FeatureSource) -> Option<usize> {
        self.list.iter().position(|feature| {
            !feature.removed && &*feature.name == name && &feature.source == source
        })
    }

    /// Position of the last row, if any. Includes soft-removed slots.
    pub fn last_pos(&self) -> Option<usize> {
        self.list.len().checked_sub(1)
    }

    pub fn contains(&self, name: &str, stackable: bool, source: &FeatureSource) -> bool {
        if stackable {
            self.list.iter().any(|feature| {
                !feature.removed
                    && &*feature.name == name
                    && feature.applied
                    && feature.source == *source
            })
        } else {
            self.list
                .iter()
                .any(|feature| !feature.removed && &*feature.name == name && feature.applied)
        }
    }

    pub fn has(&self, name: &str) -> bool {
        self.list
            .iter()
            .any(|feature| !feature.removed && &*feature.name == name && feature.applied)
    }

    pub fn has_category(&self, category: FeatureCategory) -> bool {
        self.list
            .iter()
            .any(|feature| !feature.removed && feature.applied && feature.category == category)
    }

    pub fn is_pending(&self, name: &str) -> bool {
        let mut has_applied = false;
        let mut has_unapplied = false;
        for feature in &self.list {
            if feature.removed || &*feature.name != name {
                continue;
            }
            if feature.applied {
                has_applied = true;
            } else {
                has_unapplied = true;
            }
        }
        !has_applied || has_unapplied
    }

    pub fn get_inputs(&self, name: &str, source: &FeatureSource) -> &[AssignInputs] {
        self.find(name, source)
            .map(|feature| feature.inputs.as_slice())
            .unwrap_or_default()
    }

    /// Push a fully-formed `Feature` row as-is and return its position.
    /// Skip the slot-keyed upsert that `put` does — caller owns the
    /// `Feature` and intends to land it verbatim.
    pub fn push(&mut self, feature: Feature) -> usize {
        let idx = self.list.len();
        self.list.push(feature);
        idx
    }

    /// Reuse an existing `(name, source)` slot if present (reviving a
    /// soft-removed row), otherwise push a fresh one. Returns its position.
    #[allow(clippy::too_many_arguments)]
    pub fn put(
        &mut self,
        name: &str,
        label: Option<String>,
        description: String,
        category: FeatureCategory,
        source: FeatureSource,
        inputs: Vec<AssignInputs>,
        applied: bool,
    ) -> usize {
        // Raw scan — must see removed rows so they get revived, not duplicated.
        if let Some((idx, feature)) = self
            .list
            .iter_mut()
            .enumerate()
            .rfind(|(_, feature)| &*feature.name == name && feature.source == source)
        {
            feature.removed = false;
            feature.applied = applied;
            feature.label = label;
            feature.description = description;
            feature.category = category;
            feature.source = source;
            feature.inputs = inputs;
            idx
        } else {
            let idx = self.list.len();
            self.list.push(Feature {
                name: name.into(),
                label,
                description,
                applied,
                category,
                source,
                inputs,
                replaces: None,
                removed: false,
            });
            idx
        }
    }

    /// Soft-remove the row at `idx`: flag it without shrinking the Vec so
    /// reactive_stores indexers stay in bounds. Evicts `data[name]` when no
    /// other live row carries the name. Rebuild scans the flag to surface
    /// `RebuildReason::FeatureRemoved`.
    pub fn remove(&mut self, idx: usize) {
        let Some(feature) = self.list.get_mut(idx) else {
            return;
        };
        if feature.removed {
            return;
        }
        feature.removed = true;
        let name = feature.name.clone();
        if !self
            .list
            .iter()
            .any(|other| !other.removed && other.name == name)
        {
            self.data.remove(&name);
        }
    }

    /// Truncate the feature list at the position of the entry matching
    /// `name` + `source`, dropping that feature and everything after it.
    /// Only called on a non-reactive clone (`feature_row.rs:269`), so a
    /// hard `Vec::truncate` is safe — no reactive_stores subscribers.
    pub fn truncate(&mut self, name: &str, source: &FeatureSource) -> bool {
        let Some(idx) = self
            .list
            .iter()
            .position(|feature| &*feature.name == name && &feature.source == source)
        else {
            return false;
        };
        self.list.truncate(idx);
        true
    }

    // Raw data accessors for explicit BTreeMap access where Deref coercion
    // isn't convenient (e.g. cloning, passing as function argument).

    pub fn data(&self) -> &BTreeMap<Box<str>, FeatureData> {
        &self.data
    }

    pub fn data_mut(&mut self) -> &mut BTreeMap<Box<str>, FeatureData> {
        &mut self.data
    }

    /// Split-borrow `list` and `data` simultaneously so callers can read a
    /// feature name from `list` while mutating its `data` entry.
    pub fn split_mut(&mut self) -> (&[Feature], &mut BTreeMap<Box<str>, FeatureData>) {
        (&self.list, &mut self.data)
    }

    // Per-feature data helpers.

    /// Shorthand for `data.get(name).and_then(|entry| entry.spells.as_ref())`.
    pub fn spell_data(&self, name: &str) -> Option<&SpellData> {
        self.data.get(name).and_then(|entry| entry.spells.as_ref())
    }

    /// Shorthand for `data.get_mut(name).and_then(|entry|
    /// entry.spells.as_mut())`.
    pub fn spell_data_mut(&mut self, name: &str) -> Option<&mut SpellData> {
        self.data
            .get_mut(name)
            .and_then(|entry| entry.spells.as_mut())
    }

    /// Zero `used` on every Points/Die field and every spell's `free_uses`
    /// across all data entries.
    pub fn reset_uses(&mut self) {
        for entry in self.data.values_mut() {
            for field in &mut entry.fields {
                match &mut field.value {
                    FeatureValue::Points { used, .. } | FeatureValue::Die { used, .. } => {
                        *used = 0;
                    }
                    _ => {}
                }
            }
            if let Some(spell_data) = entry.spells.as_mut() {
                for spell in &mut spell_data.spells {
                    if let Some(fu) = spell.free_uses.as_mut() {
                        fu.used = 0;
                    }
                }
            }
        }
    }

    /// Clear labels and descriptions on list entries and all data fields/
    /// spells.
    pub fn clear_all_labels(&mut self) {
        for feature in &mut self.list {
            feature.label = None;
            feature.description.clear();
        }
        for entry in self.data.values_mut() {
            for field in &mut entry.fields {
                field.label = None;
                field.description.clear();
                for opt in field.value.choices_mut() {
                    opt.label = None;
                    opt.description.clear();
                }
            }
            if let Some(spells) = &mut entry.spells {
                for spell in &mut spells.spells {
                    spell.label = None;
                    spell.description.clear();
                }
                for spell in spells.known.iter_mut().flatten() {
                    spell.label = None;
                    spell.description.clear();
                }
            }
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Default, Store)]
pub struct AssignInputs {
    #[serde(default)]
    pub args: Vec<i32>,
    #[serde(default)]
    pub dice: DicePool,
}

impl AssignInputs {
    pub fn is_empty(&self) -> bool {
        self.args.is_empty() && self.dice.is_empty()
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Default, Store)]
pub struct FeatureData {
    #[serde(default)]
    pub fields: Vec<FeatureField>,
    #[serde(default)]
    pub spells: Option<SpellData>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Store)]
pub struct FeatureField {
    pub name: String,
    #[serde(default)]
    pub label: Option<String>,
    #[serde(default)]
    pub description: String,
    #[serde(default)]
    pub value: FeatureValue,
}

impl FeatureField {
    pub fn label(&self) -> &str {
        self.label.as_deref().unwrap_or(&self.name)
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Store)]
pub enum FeatureValue {
    Points { used: u32, max: u32 },
    Choice { options: Vec<FeatureOption> },
    Die { die: Die, used: u32 },
    Bonus(i32),
}

impl Default for FeatureValue {
    fn default() -> Self {
        FeatureValue::Points { used: 0, max: 0 }
    }
}

/// Derive a short abbreviation from a name by taking the first letter of each
/// word. "Channel Divinity" → "CD", "Sorcery Points" → "SP", "Rages" → "R"
pub fn short_name(name: &str) -> String {
    name.split_whitespace()
        .filter_map(|w| w.chars().next())
        .flat_map(char::to_uppercase)
        .collect()
}

impl FeatureValue {
    pub fn available_points(&self) -> Option<u32> {
        match self {
            FeatureValue::Points { used, max } => Some(max.saturating_sub(*used)),
            FeatureValue::Die { die, used } => Some(die.amount.saturating_sub(*used)),
            _ => None,
        }
    }

    pub fn max_points(&self) -> Option<u32> {
        match self {
            FeatureValue::Points { max, .. } => Some(*max),
            FeatureValue::Die { die, .. } => Some(die.amount),
            _ => None,
        }
    }

    pub fn choices(&self) -> &[FeatureOption] {
        match self {
            FeatureValue::Choice { options } => options,
            _ => &[],
        }
    }

    pub fn choices_mut(&mut self) -> &mut [FeatureOption] {
        match self {
            FeatureValue::Choice { options } => options,
            _ => &mut [],
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Default, Store)]
pub struct FeatureOption {
    pub name: String,
    #[serde(default)]
    pub label: Option<String>,
    #[serde(default)]
    pub description: String,
    #[serde(default)]
    pub cost: u32,
    /// Set when this option is an action menu item (e.g. Innate Sorcery cast
    /// button). `None` for stored-choice picks. Filled by `sync_labels` from
    /// the registry definition; persisted so renderers don't need a
    /// `feat.actions` lookup.
    #[serde(default)]
    pub action: Option<ActionType>,
}

impl FeatureOption {
    pub fn label(&self) -> &str {
        self.label.as_deref().unwrap_or(&self.name)
    }

    pub fn set_label(&mut self, value: String) {
        self.label = Some(value);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn features_data_drops_null_entries() {
        let json = serde_json::json!({
            "list": [],
            "data": {
                "Tough": null,
                "Versatile": { "fields": [], "spells": null }
            }
        });
        let features: Features = serde_json::from_value(json).expect("deserialize");
        assert!(!features.data.contains_key("Tough"));
        assert!(features.data.contains_key("Versatile"));
    }

    #[test]
    fn features_put_returns_position() {
        let mut features = Features::default();
        let pos = features.put(
            "Alert",
            None,
            String::new(),
            FeatureCategory::General,
            FeatureSource::User(0),
            Vec::new(),
            true,
        );
        assert_eq!(pos, 0);
        assert_eq!(&*features.at(pos).unwrap().name, "Alert");

        let pos2 = features.put(
            "Tough",
            None,
            String::new(),
            FeatureCategory::General,
            FeatureSource::User(1),
            Vec::new(),
            true,
        );
        assert_eq!(pos2, 1);
        assert_eq!(&*features.at(pos2).unwrap().name, "Tough");
    }

    #[test]
    fn features_find_pos_locates_stackable() {
        let mut features = Features::default();
        features.put(
            "ASI",
            None,
            String::new(),
            FeatureCategory::General,
            FeatureSource::User(4),
            Vec::new(),
            true,
        );
        features.put(
            "ASI",
            None,
            String::new(),
            FeatureCategory::General,
            FeatureSource::User(8),
            Vec::new(),
            true,
        );
        let p4 = features.find_pos("ASI", &FeatureSource::User(4));
        let p8 = features.find_pos("ASI", &FeatureSource::User(8));
        assert_eq!(p4, Some(0));
        assert_eq!(p8, Some(1));
        assert_eq!(features.find_pos("ASI", &FeatureSource::User(12)), None);
    }

    #[test]
    fn features_at_and_last_pos() {
        let mut features = Features::default();
        assert!(features.is_empty());
        assert_eq!(features.last_pos(), None);
        assert!(features.at(0).is_none());

        let pos = features.put(
            "Tough",
            None,
            String::new(),
            FeatureCategory::General,
            FeatureSource::User(0),
            Vec::new(),
            true,
        );
        assert_eq!(features.last_pos(), Some(pos));
        assert!(!features.is_empty());
        assert_eq!(features.len(), 1);
    }

    #[test]
    fn features_put_overwrites_existing_slot_idempotently() {
        // `(name, source)` is a unique slot. A second `put` to the same slot
        // — applied or not — must overwrite that single row, never duplicate.
        let mut features = Features::default();
        let source = FeatureSource::Class("Fighter".into(), 4);
        features.put(
            "Tough",
            None,
            String::new(),
            FeatureCategory::General,
            source.clone(),
            Vec::new(),
            true,
        );
        let pos = features.put(
            "Tough",
            None,
            "updated".into(),
            FeatureCategory::General,
            source.clone(),
            vec![AssignInputs::default()],
            true,
        );
        assert_eq!(features.len(), 1);
        assert_eq!(pos, 0);
        let row = features.at(pos).unwrap();
        assert_eq!(row.description, "updated");
        assert_eq!(row.inputs.len(), 1);
    }

    #[test]
    fn features_put_does_not_reuse_unapplied_at_different_source() {
        // Stackable feat (e.g. Skilled) lands on two slots: a Species(Human)
        // swap pending insufficient inputs (applied=false) and a
        // Background(Noble) original. The second `put` must NOT silently
        // adopt the first slot — otherwise both instances collapse onto one
        // row and one source is lost.
        let mut features = Features::default();
        let species = FeatureSource::Species("Human".into());
        let background = FeatureSource::Background("Noble".into());

        // First put: pending swap, applied=false (inputs insufficient).
        features.put(
            "Skilled",
            None,
            String::new(),
            FeatureCategory::Origin,
            species.clone(),
            Vec::new(),
            false,
        );
        // Second put: same name, different source, applied=true.
        features.put(
            "Skilled",
            None,
            String::new(),
            FeatureCategory::Origin,
            background.clone(),
            Vec::new(),
            true,
        );

        assert_eq!(features.len(), 2);
        let species_row = features.find("Skilled", &species).expect("species row");
        assert!(!species_row.applied);
        let background_row = features
            .find("Skilled", &background)
            .expect("background row");
        assert!(background_row.applied);
    }

    #[test]
    fn remove_flags_row_and_evicts_data() {
        let mut features = Features::default();
        let pos = features.put(
            "Tough",
            None,
            String::new(),
            FeatureCategory::General,
            FeatureSource::User(0),
            Vec::new(),
            true,
        );
        features.data.insert("Tough".into(), FeatureData::default());

        features.remove(pos);

        assert_eq!(features.len(), 1, "Vec keeps the row");
        assert!(features.list[0].removed, "flag set");
        assert!(features.at(pos).is_none(), "soft-removed hidden from at()");
        assert!(!features.data.contains_key("Tough"), "data evicted");
    }

    #[test]
    fn remove_keeps_data_when_other_live_row_shares_name() {
        // Two ASI instances (stackable). Removing one must keep data alive
        // for the other.
        let mut features = Features::default();
        features.put(
            "ASI",
            None,
            String::new(),
            FeatureCategory::General,
            FeatureSource::User(4),
            Vec::new(),
            true,
        );
        features.put(
            "ASI",
            None,
            String::new(),
            FeatureCategory::General,
            FeatureSource::User(8),
            Vec::new(),
            true,
        );
        features.data.insert("ASI".into(), FeatureData::default());

        features.remove(0);

        assert_eq!(features.len(), 2, "both rows kept (one flagged)");
        assert!(features.list[0].removed);
        assert!(!features.list[1].removed);
        assert!(features.data.contains_key("ASI"));
    }

    #[test]
    fn remove_out_of_bounds_is_noop() {
        let mut features = Features::default();
        features.remove(0);
        features.remove(99);
        assert!(features.is_empty());
    }

    #[test]
    fn put_revives_soft_removed_slot() {
        let mut features = Features::default();
        let pos = features.put(
            "Skilled",
            None,
            String::new(),
            FeatureCategory::Origin,
            FeatureSource::User(1),
            Vec::new(),
            true,
        );
        features.remove(pos);
        assert!(features.list[pos].removed);

        let pos2 = features.put(
            "Skilled",
            None,
            String::new(),
            FeatureCategory::Origin,
            FeatureSource::User(1),
            Vec::new(),
            true,
        );

        assert_eq!(pos, pos2, "same slot reused");
        assert_eq!(features.len(), 1, "no new row");
        assert!(!features.list[pos].removed, "flag cleared");
    }

    #[test]
    fn find_skips_removed_rows() {
        let mut features = Features::default();
        let pos = features.put(
            "Tough",
            None,
            String::new(),
            FeatureCategory::General,
            FeatureSource::User(0),
            Vec::new(),
            true,
        );
        features.remove(pos);
        assert!(features.find("Tough", &FeatureSource::User(0)).is_none());
        assert!(!features.contains("Tough", false, &FeatureSource::User(0)));
        assert!(!features.has("Tough"));
    }

    #[test]
    fn serialize_drops_removed_rows() {
        let mut features = Features::default();
        features.put(
            "Live",
            None,
            String::new(),
            FeatureCategory::General,
            FeatureSource::User(0),
            Vec::new(),
            true,
        );
        let pos = features.put(
            "Dead",
            None,
            String::new(),
            FeatureCategory::General,
            FeatureSource::User(0),
            Vec::new(),
            true,
        );
        features.remove(pos);

        let json = serde_json::to_value(&features).expect("serialize");
        let list = json
            .get("list")
            .and_then(|value| value.as_array())
            .expect("list array");
        assert_eq!(list.len(), 1, "removed row dropped");
        assert_eq!(
            list[0].get("name").and_then(|name| name.as_str()),
            Some("Live"),
        );
    }
}
